# Optimising the model
 ## 1. Encoding and scaling

In [1]:
#import dependencies


In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import balanced_accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score, roc_auc_score
from sklearn.metrics import accuracy_score



## split data into training and data sets


In [4]:
#read the dummied data csv file 

In [5]:
df=pd.read_csv("https://media.githubusercontent.com/media/DanielHughes1580/Project_4_Group_5/main/Data_Cleaned/dummied_data_add_clean.csv",index_col=0)
df.head()


Number of Children  Annual Income  Age  Months Employed  Family Members  \
0                   0       427500.0   32             4542             2.0   
1                   0       427500.0   32             4542             2.0   
2                   0       427500.0   32             4542             2.0   
3                   0       427500.0   32             4542             2.0   
4                   0       427500.0   32             4542             2.0   

   Months Since Payment Status  Gender_F  Owns a Car_Y  Owns Property_Y  ...  \
0                     0   Paid     False          True             True  ...   
1                     1   Paid     False          True             True  ...   
2                     2   Paid     False          True             True  ...   
3                     3   Paid     False          True             True  ...   
4                     4   Paid     False          True             True  ...   

   Occupation_Managers  Occupation_Medicine staff  Occupation_Not Specified  \
0                False                      False                      True   
1                False                      False                      True   
2                False                      False                      True   
3                False                      False                      True   
4                False                      False                      True   

   Occupation_Pensioner  Occupation_Private service staff  \
0                 False                             False   
1                 False                             False   
2                 False                             False   
3                 False                             False   
4                 False                             False   

   Occupation_Realty agents  Occupation_Sales staff  Occupation_Secretaries  \
0                     False                   False                   False   
1                     False                   False                   False   
2                     False                   False                   False   
3                     False                   False                   False   
4                     False                   False                   False   

   Occupation_Security staff  Occupation_Waiters/barmen staff  
0                      False                            False  
1                      False                            False  
2                      False                            False  
3                      False                            False  
4                      False                            False  

[5 rows x 49 columns]

In [6]:
## Encoding Outputs

#import dependencies
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split
import pandas as pd


In [7]:
# Convert categorical labels to numerical labels
label_encoder = LabelEncoder()
df['status_encoded'] = label_encoder.fit_transform(df['Status'])
# Convert numerical labels to one-hot encoded format
onehot_encoder = OneHotEncoder()
encoded_status = onehot_encoder.fit_transform(df['status_encoded'].values.reshape(-1, 1)).toarray()

In [8]:
# Split the preprocessed data into our features and target arrays
# Features
X = df.drop(columns=['Status', 'status_encoded'])
# Target variable
y = encoded_status


In [9]:
X.head()

Number of Children  Annual Income  Age  Months Employed  Family Members  \
0                   0       427500.0   32             4542             2.0   
1                   0       427500.0   32             4542             2.0   
2                   0       427500.0   32             4542             2.0   
3                   0       427500.0   32             4542             2.0   
4                   0       427500.0   32             4542             2.0   

   Months Since Payment  Gender_F  Owns a Car_Y  Owns Property_Y  \
0                     0     False          True             True   
1                     1     False          True             True   
2                     2     False          True             True   
3                     3     False          True             True   
4                     4     False          True             True   

   Income Category_Commercial associate  ...  Occupation_Managers  \
0                                 False  ...                False   
1                                 False  ...                False   
2                                 False  ...                False   
3                                 False  ...                False   
4                                 False  ...                False   

   Occupation_Medicine staff  Occupation_Not Specified  Occupation_Pensioner  \
0                      False                      True                 False   
1                      False                      True                 False   
2                      False                      True                 False   
3                      False                      True                 False   
4                      False                      True                 False   

   Occupation_Private service staff  Occupation_Realty agents  \
0                             False                     False   
1                             False                     False   
2                             False                     False   
3                             False                     False   
4                             False                     False   

   Occupation_Sales staff  Occupation_Secretaries  Occupation_Security staff  \
0                   False                   False                      False   
1                   False                   False                      False   
2                   False                   False                      False   
3                   False                   False                      False   
4                   False                   False                      False   

   Occupation_Waiters/barmen staff  
0                            False  
1                            False  
2                            False  
3                            False  
4                            False  

[5 rows x 48 columns]

In [10]:
#Select the first 5 elements of the array
print(y[:5])



[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [11]:
# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)




In [12]:
X_train.shape

(619376, 48)

In [13]:
X_test.shape

(154845, 48)

In [14]:
# Create a StandardScaler instance
scaler = StandardScaler()
# Fit the StandardScaler
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print(scaler.transform(X_train_scaled))

C:\Users\ayomi\anaconda3\envs\dev\lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


[[-1.43137336 -1.8533974  -3.77559206 ... -1.06777095 -1.1414655
  -1.06066329]
 [-1.43137336 -1.85338697 -3.90985734 ... -1.06777095 -1.1414655
  -1.06066329]
 [-1.43137336 -1.85339566 -3.72030636 ... -1.06777095 -1.1414655
  -1.06066329]
 ...
 [-1.43137336 -1.8533848  -3.79138798 ... -1.06777095 -1.1414655
  -1.06066329]
 [-1.43137336 -1.8533987  -3.89406143 ... -1.06777095 -1.1414655
  -1.06066329]
 [ 0.57066756 -1.85339783 -3.96514305 ... -1.06777095 -1.1414655
  -1.06066329]]


In [15]:
# Assuming Y_train is one-hot encoded
y_train_labels = np.argmax(y_train, axis=1)
y_test_labels = np.argmax(y_test, axis=1)


## Train the Logistic Regression classifier and fit the trained data to predict

In [29]:

logreg_classifier = LogisticRegression(multi_class='ovr', max_iter=2000, random_state=42)
print(f"classifier: {logreg_classifier}")

logreg_classifier.fit(X_train_scaled, y_train_labels)

classifier: LogisticRegression(max_iter=2000, multi_class='ovr', random_state=42)


LogisticRegression(max_iter=2000, multi_class='ovr', random_state=42)

In [30]:
#predict on the training data
y_pred_train = logreg_classifier.predict(X_train_scaled)
results = pd.DataFrame({"Prediction": y_pred_train, "Actual": y_train_labels}).reset_index(drop=True)
results.head(10)

Prediction  Actual
0           2       0
1           0       2
2           2       0
3           2       2
4           2       0
5           2       2
6           0       1
7           2       0
8           2       2
9           2       2

In [31]:
#predict on the test data
y_pred_test = logreg_classifier.predict(X_test_scaled)
results = pd.DataFrame({"Prediction": y_pred_test, "Actual": y_test_labels}).reset_index(drop=True)
results.head(10)

Prediction  Actual
0           2       2
1           0       2
2           2       2
3           2       0
4           2       0
5           2       1
6           2       0
7           2       0
8           2       1
9           0       1

## Evaluating performance of training set- accuracy, confusion matrix and classification report

In [33]:
#evaluating performance of test set
accuracy = accuracy_score(y_test_labels, y_pred_test)
f1 = f1_score(y_test_labels, y_pred_test, average='weighted')
precision = precision_score(y_test_labels, y_pred_test, average='weighted', zero_division=0)
recall = recall_score(y_test_labels, y_pred_test, average='weighted', zero_division=0)

print('Model Performance of Test set')
print(f'Training Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'Training Precision: {precision}')
print(f'Recall ratio: {recall}')




Model Performance of Test set
Training Accuracy: 0.47581129516613385
F1 Score: 0.4213623226527988
Training Precision: 0.3843569292824845
Recall ratio: 0.47581129516613385


In [34]:
#evaluating performance of training set
accuracy = accuracy_score(y_train_labels, y_pred_train)
f1 = f1_score(y_train_labels, y_pred_train, average='weighted')
precision = precision_score(y_train_labels, y_pred_train, average='weighted', zero_division=0)
recall = recall_score(y_train_labels, y_pred_train, average='weighted', zero_division=0)

print('Model Performance of Training set')
print(f'Training Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'Training Precision: {precision}')
print(f'Recall ratio: {recall}')



Model Performance of Training set
Training Accuracy: 0.47684120792539586
F1 Score: 0.42281001631987275
Training Precision: 0.38623161914937515
Recall ratio: 0.47684120792539586


In [35]:
# Generate a confusion matrix for the model
confusion_matrix(y_test_labels, y_pred_test)

array([[27397,     0, 32366],
       [12103,     0, 17194],
       [19505,     0, 46280]], dtype=int64)

In [36]:
# Print the classification report for the model

target_names = ["paid", "Overdue", "no loan taken"]
print(classification_report(y_test_labels, y_pred_test, target_names=target_names, zero_division=0))


               precision    recall  f1-score   support

         paid       0.46      0.46      0.46     59763
      Overdue       0.00      0.00      0.00     29297
no loan taken       0.48      0.70      0.57     65785

     accuracy                           0.48    154845
    macro avg       0.32      0.39      0.34    154845
 weighted avg       0.38      0.48      0.42    154845



## 2. using grid search cross-validation and a pipeline that includes preprocessing steps such as oversampling and feature scaling.


In [40]:
#import dependencies
from imblearn.over_sampling import RandomOverSampler, SMOTE
from sklearn.model_selection import GridSearchCV
from imblearn.pipeline import Pipeline

In [41]:
# Define the logistic regression model
logreg = LogisticRegression()



In [47]:
# Define the parameter grid to search
param_grid = {
    'classifier__solver': ['sag', 'lbfgs'],
    'classifier__C': [0.01, 0.1, 1.0],
    'classifier__max_iter': [100, 500, 1000]
}




In [44]:
# Create a pipeline with oversampling and logistic regression
pipeline = Pipeline([
    ('sampling', RandomOverSampler()),
    ('scaler', StandardScaler()),
    ('classifier', logreg)
])


In [ ]:
# Perform grid search cross-validation
grid_search = GridSearchCV(pipeline, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_scaled, y_train_labels)

In [68]:
# Print the best parameters found
print("Best Parameters:", grid_search.best_params_)

Best Parameters: {'classifier__C': 1.0, 'classifier__max_iter': 100, 'classifier__solver': 'sag'}


In [69]:
# Evaluate the model performance
print("Training Accuracy:", grid_search.best_score_)
print("Test Accuracy:", grid_search.best_estimator_.score(X_test_scaled, y_test_labels))

Training Accuracy: 0.4332134280043528
Test Accuracy: 0.43163163163163165


In [70]:
#predict results
y_preds = grid_search.best_estimator_.predict(X_test_scaled)
results = pd.DataFrame({"Prediction": y_preds, "Actual": y_test_labels}).reset_index(drop=True)
results.head(10)

Prediction  Actual
0           2       2
1           0       2
2           2       2
3           1       0
4           0       0
5           2       1
6           2       0
7           1       0
8           2       1
9           1       1

In [71]:

# Calculate the confusion matrix
conf_matrix = confusion_matrix(y_test_labels, y_preds)

# Print the confusion matrix
print("Confusion Matrix:")
print(conf_matrix)


Confusion Matrix:
[[23888 11051 24824]
 [10070  6178 13049]
 [17068 11947 36770]]


## 3. Random Over Sampling or SMOTE

In [66]:
# Initialize RandomOverSampler
ros = RandomOverSampler(random_state=42)
# Initialize SMOTE
smote = SMOTE(random_state=42)

In [72]:
# For Random Over-sampling
X_resamplled, y_resamplled = ros.fit_resample(X_train_scaled, y_train_labels)


In [75]:
# Initialize Logistic Regression model with SAG solver
logreg_sag = LogisticRegression(solver='sag', multi_class='ovr', max_iter=2000, random_state=42)
print(f"classifier: {logreg_sag}")

classifier: LogisticRegression(max_iter=2000, multi_class='ovr', random_state=42,
                   solver='sag')


In [76]:
# Fit the model to your resampled data
logreg_sag.fit(X_resamplled, y_resamplled)


LogisticRegression(max_iter=2000, multi_class='ovr', random_state=42,
                   solver='sag')

In [77]:
#predict on the test data
y_predss = logreg_sag.predict(X_test_scaled)
results = pd.DataFrame({"Prediction": y_predss, "Actual": y_test_labels}).reset_index(drop=True)
results.head(10)

Prediction  Actual
0           2       2
1           0       2
2           2       2
3           1       0
4           0       0
5           2       1
6           2       0
7           1       0
8           2       1
9           1       1

In [90]:
#predict on the training data
y_predss_train = logreg_sag.predict(X_train_scaled)
results = pd.DataFrame({"Prediction": y_predss_train, "Actual": y_train_labels}).reset_index(drop=True)
results.head(10)

Prediction  Actual
0           2       0
1           0       2
2           2       0
3           1       2
4           1       0
5           2       2
6           0       1
7           2       0
8           2       2
9           2       2

In [79]:
#evaluating performance of test set
accuracy = accuracy_score(y_test_labels, y_predss)
f1 = f1_score(y_test_labels, y_predss, average='weighted')
precision = precision_score(y_test_labels, y_predss, average='weighted', zero_division=0)
recall = recall_score(y_test_labels, y_predss, average='weighted', zero_division=0)

print('Model Performance of Test set')
print(f'Training Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'Training Precision: {precision}')
print(f'Recall ratio: {recall}')

# Print the classification report for the model

target_names = ["paid", "Overdue", "no loan taken"]
print(classification_report(y_test_labels, y_predss, target_names=target_names, zero_division=0))




Model Performance of Test set
Training Accuracy: 0.43588750040362945
F1 Score: 0.4308245148594183
Training Precision: 0.42997662938129483
Recall ratio: 0.43588750040362945
               precision    recall  f1-score   support

         paid       0.47      0.41      0.44     59763
      Overdue       0.21      0.19      0.20     29297
no loan taken       0.49      0.57      0.53     65785

     accuracy                           0.44    154845
    macro avg       0.39      0.39      0.39    154845
 weighted avg       0.43      0.44      0.43    154845



In [91]:
#evaluating performance of training set
accuracy = accuracy_score(y_train_labels, y_predss_train)
f1 = f1_score(y_train_labels, y_predss_train, average='weighted')
precision = precision_score(y_train_labels, y_predss_train, average='weighted', zero_division=0)
recall = recall_score(y_train_labels, y_predss_train, average='weighted', zero_division=0)

print('Model Performance of train set')
print(f'Training Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'Training Precision: {precision}')
print(f'Recall ratio: {recall}')

# Print the classification report for the model

target_names = ["paid", "Overdue", "no loan taken"]
print(classification_report(y_train_labels, y_predss_train, target_names=target_names, zero_division=0))




Model Performance of train set
Training Accuracy: 0.43654904290770064
F1 Score: 0.43187526035674273
Training Precision: 0.4313904557005694
Recall ratio: 0.43654904290770064
               precision    recall  f1-score   support

         paid       0.47      0.41      0.44    240215
      Overdue       0.21      0.19      0.20    116127
no loan taken       0.49      0.57      0.53    263034

     accuracy                           0.44    619376
    macro avg       0.39      0.39      0.39    619376
 weighted avg       0.43      0.44      0.43    619376



## 4. Regularisation and balancing weights

In [80]:
logreg_l1 = LogisticRegression(penalty='l1', solver='saga', multi_class='ovr', class_weight='balanced', max_iter=1000)
print(f"classifier: {logreg_l1}")
logreg_l1.fit(X_resamplled, y_resamplled)

classifier: LogisticRegression(class_weight='balanced', max_iter=1000, multi_class='ovr',
                   penalty='l1', solver='saga')


LogisticRegression(class_weight='balanced', max_iter=1000, multi_class='ovr',
                   penalty='l1', solver='saga')

In [84]:
y_predsss = logreg_sag.predict(X_test_scaled)
results = pd.DataFrame({"Prediction": y_predsss, "Actual": y_test_labels}).reset_index(drop=True)
results.head(10)

Prediction  Actual
0           2       2
1           0       2
2           2       2
3           1       0
4           0       0
5           2       1
6           2       0
7           1       0
8           2       1
9           1       1

In [86]:
y_predsss_train = logreg_sag.predict(X_train_scaled)
results = pd.DataFrame({"Prediction": y_predsss_train, "Actual": y_train_labels}).reset_index(drop=True)
results.head(10)

Prediction  Actual
0           2       0
1           0       2
2           2       0
3           1       2
4           1       0
5           2       2
6           0       1
7           2       0
8           2       2
9           2       2

In [87]:
#evaluating performance of test set
accuracy = accuracy_score(y_test_labels, y_predsss)
f1 = f1_score(y_test_labels, y_predsss, average='weighted')
precision = precision_score(y_test_labels, y_predsss, average='weighted', zero_division=0)
recall = recall_score(y_test_labels, y_predsss, average='weighted', zero_division=0)

print('Model Performance of Test set')
print(f'Training Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'Training Precision: {precision}')
print(f'Recall ratio: {recall}')

# Print the classification report for the model

target_names = ["paid", "Overdue", "no loan taken"]
print(classification_report(y_test_labels, y_predsss, target_names=target_names, zero_division=0))


Model Performance of Test set
Training Accuracy: 0.43588750040362945
F1 Score: 0.4308245148594183
Training Precision: 0.42997662938129483
Recall ratio: 0.43588750040362945
               precision    recall  f1-score   support

         paid       0.47      0.41      0.44     59763
      Overdue       0.21      0.19      0.20     29297
no loan taken       0.49      0.57      0.53     65785

     accuracy                           0.44    154845
    macro avg       0.39      0.39      0.39    154845
 weighted avg       0.43      0.44      0.43    154845



In [89]:
#evaluating performance of training set
accuracy = accuracy_score(y_train_labels, y_predsss_train)
f1 = f1_score(y_train_labels, y_predsss_train, average='weighted')
precision = precision_score(y_train_labels, y_predsss_train, average='weighted', zero_division=0)
recall = recall_score(y_train_labels, y_predsss_train, average='weighted', zero_division=0)

print('Model Performance of Train set')
print(f'Training Accuracy: {accuracy}')
print(f'F1 Score: {f1}')
print(f'Training Precision: {precision}')
print(f'Recall ratio: {recall}')

# Print the classification report for the model

target_names = ["paid", "Overdue", "no loan taken"]
print(classification_report(y_train_labels, y_predsss_train, target_names=target_names, zero_division=0))


Model Performance of Train set
Training Accuracy: 0.43654904290770064
F1 Score: 0.43187526035674273
Training Precision: 0.4313904557005694
Recall ratio: 0.43654904290770064
               precision    recall  f1-score   support

         paid       0.47      0.41      0.44    240215
      Overdue       0.21      0.19      0.20    116127
no loan taken       0.49      0.57      0.53    263034

     accuracy                           0.44    619376
    macro avg       0.39      0.39      0.39    619376
 weighted avg       0.43      0.44      0.43    619376

